plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'cn.erhio.deeper'
    compileSdk 34

    defaultConfig {
        applicationId "cn.erhio.deeper"
        minSdk 21
        targetSdk 34
        versionCode 2
        versionName "1.1.0"
    }

    signingConfigs {
        release {
            storeFile rootProject.file('keystore/deeper.keystore')
            storePassword 'deeper-release-key'
            keyAlias 'deeper'
            keyPassword 'deeper-release-key'
        }
    }

    flavorDimensions "pack"
    productFlavors {
        std {
            dimension "pack"
        }
        full {
            dimension "pack"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }

    applicationVariants.all { variant ->
        variant.outputs.all { output ->
            def abi = output.getFilter(com.android.build.OutputFile.ABI)
            def flavor = abi ? "${variant.flavorName}-${abi}" : variant.flavorName
            outputFileName = "DeepEr-${variant.versionName}-${flavor}-${variant.buildType.name}.apk"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    buildFeatures {
        viewBinding true
    }

    androidResources {
        noCompress += 'onnx'
    }

    splits {
        abi {
            enable true
            reset()
            include 'arm64-v8a', 'armeabi-v7a', 'x86_64'
            universalApk false
        }
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.webkit:webkit:1.10.0'
    implementation 'com.microsoft.onnxruntime:onnxruntime-android:1.18.0'
}
